---
# tasks file for common
- name: Adding TXLF Staff Group
  group: name=txlf-staff state=present

- name:  Adding Users
  user: name={{ item.key }} groups={{ item.value.groups }}
  with_dict: "{{ users }}"

- name: Adding SSH Keys
  sudo: yes
  authorized_key: user={{ item.key }} key="{{ item.value.pubkey }}"
  with_dict: "{{ users }}"

- name: Adjusting Sudoers File
  lineinfile:  "dest=/etc/sudoers state=present regexp='^%txlf-staff' line='%txlf-staff ALL=(ALL) NOPASSWD: ALL'"

- name:  Installing Git Client
  yum: name=git state=present

